internal/kubernetes/eventhandler.go
internal/kubernetes/limiter.go

Fix concurrency issue on cordon activity, and ensure that a node is cordon before scheduling any drain activity

Fix concurrency on restart + ensure cordon before drain

---

cmd/draino/draino.go
helm/draino/values.yaml
internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/podfilters.go
internal/kubernetes/util_test.go
internal/kubernetes/watch.go
internal/kubernetes/watch_test.go

Code for issue [#94](https://github.com/planetlabs/draino/issues/94)
This will allow us to avoid going to the cordon step if we detect that one of the pods on the node cannot be drained later.

cordon exclude filters

---

README.md
cmd/draino/draino.go
internal/kubernetes/drainer.go
internal/kubernetes/eventhandler.go
internal/kubernetes/limiter.go
internal/kubernetes/limiter_test.go
internal/kubernetes/nodefilters.go
internal/kubernetes/nodefilters_test.go
internal/kubernetes/podfilters.go
internal/kubernetes/util.go

This PR allows Draino to take care of PVC/PV in case a statefulset pods is annotated (opt-in) for that feature.
So far the annotation specify the storage class for which we want to do this cleanup. I will open discussion with users to understand if this a good idea to given them control on that, or if they prefer this to be 100% driven by draino (storage class configured inside draino).
This PR also has some linting of existing code.

delete PVC/PV after eviction for annotated pods

---

cmd/draino/draino.go
helm/draino/values.yaml
internal/kubernetes/nodefilters.go
internal/kubernetes/nodefilters_test.go

Fix # 107 upstream issue
There are 2 ways of filtering nodes that are in scope. If using `node-label`, an AND operator is applied (to keep historic behavior).
The problem is that if the user provide the parameter twice with the same Key and different value, only one of the 2 value is taken into account. Somehow the program is silently failing: it is not doing a AND that would result in an empty intersection, it would use one of the 2 values.

David.benque/issue 107

---

cmd/draino/draino.go
internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/util.go

Thanks to this PR draino creates drain schedules per groups of nodes. We use to have one drain scheduled every 3 minutes for the whole cluster. Now it is possible to have a drain scheduled every 3min per drain-group. For example if the drain group is defined like:
```
--drain-buffer=3m
--drain-group-labels=nodegroups.datadoghq.com/namespace
```
that means that we can have a drain scheduled every 3 minutes in each namespace.
If we do:
```
--drain-buffer=3m
--drain-group-labels=nodegroups.datadoghq.com/namespace,nodegroups.datadoghq.com/name
```
that means that we can have d drain scheduled every 3 minutes per nodegroup.
Application owner can extend the grouping by adding their group name as annotation with `draino/drain-group`

Drain group and custom drain buffer

---

cmd/draino/draino.go
internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/util.go

This is consuming the [node replacement feature](https://github.com/DataDog/k8s-node-metadata-controller/pull/7) to tackle the case where node are block in Cordon+Drain_Completed due to minSize>0 on the NG.

request node replacement

---

cmd/draino/draino.go
internal/kubernetes/limiter.go
internal/kubernetes/limiter_test.go

I was using `flowcontrol.NewRateLimit` with `burst=0` ... it was not a good idea, it needs to be at least 1, else no request can go through the limiter.
Adding a unittest associated to that.

fix rate limiting: burst=0 is not a good idea

---

README.md
cmd/draino/draino.go
internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/drainer.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/util.go

Allow user to request node pre-provisioning before starting the drain.
This is achieved thanks to a dedicated annotation on the node to be drained.
The node pre-provisioning is done with the same API than for node-replacement but without the rate limiting.

pre-provisioning node before drain

---

cmd/draino/draino.go
internal/kubernetes/podfilters.go
internal/kubernetes/podfilters_test.go

Introduce the ability for pods to opt-in via annotation.
exampele of usage: redis pod that are sts that are excluded from the drain standard configuration but that are compliant (PDB +readiness probe + EBS).

opt-in filtering for pods

---

internal/kubernetes/drainer.go

When the deletion of the pod fails due to NotFound, we should not exit with error. It just means that the PVC cleanup was faster than the statefulset-controller that has not yet recreated the pod. In that case we should continue waiting for the PVC to be created, and possibly attempt a pod deletion again.

do not fail with error when delete pod return NotFound

---

internal/kubernetes/blocker.go
internal/kubernetes/drainer.go

When there is no blocker configured the Blocker run should wait for the stopCh signal before returning

protect runner when there is no blocker defined

---

internal/kubernetes/drainer.go

This PR gives the ability for user to set the URL of eviction API on the STS annotation instead of every pod annotation.
cc @iksaif

get url for eviction API on pod or on sts

---

cmd/draino/draino.go
internal/kubernetes/eventhandler.go
internal/kubernetes/observability.go
internal/kubernetes/util.go

Fix an issue with the filters that are passed to the observability layout: it was missing the opt-in filter
Add a new primitive to get log verbosity per node on demand: when node has the annotation `draino/logs=verbose`

fix filter for observability and add LogForVerboseNode

---

Makefile
cmd/draino/draino.go
internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/observability.go

When a drain fails, it can be due to timeout or transient context.So far it is possible to ask for a retry by adding an annotation. To improve user and operational experience we should go for automatic retry (N times) before definitively failing. After failing N times the node is uncordoned and annotation is added:
```
draino/drain-retry: failed
```
This allows draino to continue draining other nodes, rather than being blocked at the cluster level.
- New flag *max-drain-attempts-before-fail* enables feature. May be an integer number of retries defaulting to 8.
- New check in EventHandler.HandleNode to fail when retry is exceeded with "Drain Failed: MaxDrainAttempts reached".
- Modifed SchedulesGroup.addSchedule to add backoff-delay on new retry schedules
- Modified …

[COMPUTE-971] [control] automatic exponential backoff on drain retry

---

cmd/draino/draino.go
internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/eventhandler.go

Following first usage of automatic retry, I met the problem that is described in that comment in previous PR:
https://github.com/DataDog/draino/pull/36/files#r677379037
Now the for the same group we consider the nodes with retry and the nodes without retry to compute next schedule time.
Also the scheduling every 2 hours is a bit too slow, reducing it to 23 minutes. It is possible to override this value of 23 by adding a specific annotation on the node `draino/retry-delay` with the value as duration.

new strategy for scheduling retries

---

cmd/draino/draino.go
internal/kubernetes/blocker.go
internal/kubernetes/conditions_test.go
internal/kubernetes/drainSchedule.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/limiter_test.go
internal/kubernetes/nodefilters.go
internal/kubernetes/nodefilters_test.go
internal/kubernetes/observability.go
internal/kubernetes/observability_test.go
internal/kubernetes/watch.go
internal/kubernetes/watch_test.go

https://datadoghq.atlassian.net/browse/COMPUTE-1350
TLDR: concurrency case between `draino` and rollout of STS. The pod is `pending` and can't be scheduled because `draino` has cordoned the node holding the PV while the pod was recreated. When we discover that context we uncordon the node.
In order to achieve this the runtimeObjectSotre was augmented with PV and PVC + pod has now a reverse index on PVC

ensure that we are not blocking pod scheduling due to cordon on PVC/PV

---

Dockerfile
internal/kubernetes/limiter_test.go
internal/kubernetes/observability.go
internal/kubernetes/observability_test.go

Hopefully this will make it more clear to users when a node is out of
scope instead of just having the value of the annotation be empty
for https://datadoghq.atlassian.net/browse/COMPUTE-997

Use draino configuration value of out of scope

---

internal/kubernetes/eventhandler.go
internal/kubernetes/nodefilters.go
internal/kubernetes/observability.go

User can specify a list that represent the allowed-conditions. For example DRE for the first activation with Kafka clusters want to opt-in only for `disk-corruption` condition.
In the telemetry a node that has specified a list of allowed-condition will appear out of scope till it receives one of the allowed signal.

User user can specify a list of allowed conditions

---

internal/kubernetes/observability.go
internal/kubernetes/watch.go

Main fix:
The timeout value that was passed to the Retry function was `10` instead of `10*time.Second`... of course the call was almost always going to timeout with `10ns`.
Add-on:
Ignore new nodes (less than 1 minute) when generating metrics since they don't have yet all their metadata to produce accurate metrics.

David.benque/scope annotation

---

internal/kubernetes/drainSchedule.go
internal/kubernetes/drainer.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/observability.go

ability for user to specify the number of max retry attempts
+ in observability layer, requeue with delay instead of forgetting the item.

custom retry count

---

cmd/draino/draino.go
internal/kubernetes/conditions_test.go
internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go
internal/kubernetes/event_util.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/util.go

Most importantly this centralizes the node hack that's required and does
it in a type safe way
After this pr, the event recorder from the k8s `record` package should
never be used directly to create an event

Centralize all event creation

---

internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go
internal/kubernetes/eventhandler.go
internal/kubernetes/nodefilters.go
internal/kubernetes/observability.go

Three changes in that PR:
1 - If the user uncordon a node we should remove any existing schedule.
2 -If a drain start we should verify that the node is still cordon.
3- In GetUnscheduledPodsBoundToNodeByPV do not take into account fresh pending pods: the PVC cleanup might be ongoing... so let's give it chance to heppen.

remove drain schedule if a node is not cordon + do not drain if not cordon

---

cmd/draino/draino.go
internal/kubernetes/eventhandler.go
internal/kubernetes/observability.go
internal/kubernetes/util.go

We (mainly @matthieujaillais) are today processing offline report to find out what is the good strategy to onboard more applications in NLA. It turned out that one relevant way of grouping the nodes is to use the first part of the NGName.
By experience this creates relevant grouping. Instead of doing that offline and doing data post processing we want to have it done directly on the metric with a new `ng-name-prefix` tag. This way the distribution that we are today computing offline can be created directly into the dsahboard.
Let's note that this grouping is also done a lot by the dashboard users when they filter NG with values like `kafka*`, `logs*`, ...

add tag for ngName prefix

---

cmd/draino/draino.go
internal/kubernetes/klog/klog.go
internal/kubernetes/klog/main/main.go

gotchas encountered
* by default, `v` is set to `0` for klog, meaning all klog.V(1) and up
won't be logged. Defaulted this to `4`
* the default cli flag of `-v` used by klog can't be used since we use
kingpin that doesn't define its own flags the same way that klog does,
created a new draino cli flag read by kingpin named `klogVerbosity`
and forwarded its value to klog
* `klog.InitFlags(...)` sets logtostderr to true, so set this flag to
false as this isn't what we want
* there is a v1 and a v2 of klog, the same one that is configured is the
same one that must be used. Currently the version of k8s we depend on
uses klog v1, when they switch to v2 we will silently lose these logs
unless we switch to also configuring klog v2

Correctly init klog

---

cmd/draino/draino.go
internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go

For traceability, we are adding the list of conditions that have triggered the eviction in the annotation of the eviction object that is sent to the eviction++ API

add metadata that list condition on the eviction object

---

internal/kubernetes/eventhandler.go
internal/kubernetes/observability.go

if the node has a label `node-lifecycle.datadoghq.com/enabled` then the value `true|false` is used to decide to proceed or not with the cordon. In that case we don't look at the workload running in the node to decide to take it in scope or not.

bypass cordon filter if the label for opt-in/out is set on the node

---

internal/kubernetes/nodefilters.go

If the PVC is replaced by the controller manager before the check on PVC happens, the system thinks that there is a pod pending and a PVC bound to that node.
In fact only the name match in the claimRef of the PV associated with the node.
If we also check the UUID we will see that the PVC was also deleted.

check pvc UUID

---

internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go
internal/kubernetes/event_util.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/util.go

This should improve coverage but we still won't have k8s API calls
attached to trace. We need to upgrade the k8s client for this in order to be able to pass contexts.
A bunch of logs are also not using `TracedLogger` yet.

tracing: add more tracing

---

cmd/draino/draino.go
internal/kubernetes/drainer.go
internal/kubernetes/observability.go
internal/kubernetes/podfilters.go

There are some pods, like jobs, or gitlabRunner, or sparkRunnner that should not be evicted.
In such case we want to cordon the node but remove this pod from the eviction list. No eviction we wait for them to complete.
We already have an option for cordonOnly, but for gitlabRunner and sparkRunner we cannot use it because these are special cases that do not have controller (ownerReference), and so the classic feature of CordonOnly can't work because it would be overwritten by the force opt-in filter that we would have to use to bypass the check on the controller.
So here the new annotation, explicitly force-opt-in and at the same time avoid the evict activity.

Short lived pod filter

---

internal/kubernetes/eventhandler.go
internal/kubernetes/observability.go
internal/kubernetes/observability_test.go

When we label the nodes, and there is an error, the system keep trying again and again.... this is not valid if the error is IsNotFound (node was deleted).
For other error, we can wait for next iteration of the observability layer.
Today the queue are saturated by some nodes that always fail due to IsNotFound. As a consequence, other nodes cannot be updated.

don't retrive on failure for node labeling, just wait for next iteration

---

internal/kubernetes/drainSchedule.go
internal/kubernetes/drainer.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go

Previously, a "failed" node replacement would never get cleared
Now, we attempt the node replacement by setting this to `requested`
regardless of its previuos state.
Additionally
* we stop waiting when the status is set to failed
* we set the default replacement timeout to slightly longer than the
node metadata controllers node replacement timeout so the order of
events is more predictable when the replacement pod is not scheduled
See also https://github.com/DataDog/k8s-node-metadata-controller/pull/35
although it is not a strict dependency on this change.

Fix node replacement

---

internal/kubernetes/observability.go
internal/kubernetes/observability_test.go

In case the node is eligible for 2 config the label value was using a "," which is not accepted.
```
"error":"Node \"ip-10-49-244-120.ec2.internal\" is invalid: metadata.labels: Invalid value: \"database-with-local-data,standard\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"
```

Remplace "," with "." to be compliant with Label regexp

---

cmd/draino/draino.go
internal/kubernetes/observability.go
internal/kubernetes/observability_test.go

In some cases the observability layer was broken due to a label update that was not happening. Initial observations were:
- nodes were continuously added to the queue (labelling require) and that was expected
- when many nodes are added to the queue periodically, sometimes the dequeuing does not happen anymore
After investigation I figured out that the BucketRateLimiter was scheduling the processing time of the item always further in the future when the dequeuing rate was not able to sustain the pressure. Once the processing delay was increased beyond the add frequency, the items would never be processed again.
The problem is that the bucket rate limiter increase does not take into account that the item is already in the queue, it acts globally and end up increasing the delay at every …

David.benque/queue debugging

---

internal/kubernetes/drainer.go

When asking draino to "restart" after a permanent failure, we should take care of cleaning the pre-provisioning label.

On failure restart, also cleanup pre-provisioning label if it exist

---

cmd/draino/draino.go
internal/kubernetes/conditions_test.go
internal/kubernetes/config.go
internal/kubernetes/drainer.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/nodefilters.go
internal/kubernetes/nodefilters_test.go
internal/kubernetes/observability.go
internal/kubernetes/observability_test.go

We want to activate NLA by default on staging for all applications.
For applications that are having a PVC and a local PV, if nothing is done the PVC is going to be block on the cordon node after the drain.
We don't want to ask every application to opt-in for PVC management. Only application that use eviction++ url can do PVC management on their side (or not, they have to explicitly set the option).
Thanks to this PR, every application that does not use eviction++ URL will have PVC management activated by default. This is piloted by a flag `--pvc-management-by-default` at application level. The default value of the flag is `false`.

PVC management is automatically ON if there is no evictionURL defined

---

.gitlab-ci.yml

duplicate of https://github.com/DataDog/k8s-compute-diagnostics/pull/68

fix image tag value path in gitlab ci

---

internal/kubernetes/drainSchedule.go
internal/kubernetes/drainer.go

to be used as metric tag
when eviction endpoint is unreachable (e.g., CNP issue) or returns unexpected status code like 401 unauthorized

add missing eviction endpoint failure cause

---

go.mod
go.sum
internal/kubernetes/drainer.go

`draino` will use emissary and provide some auth with bearer token.
Documentation: https://datadoghq.atlassian.net/wiki/spaces/RUNTIME/pages/2649784352/Internal+Service+Authentication
it is possible to use both http et https scheme for eviction++. In case of https, we skip server verification for the moment. We will decide later when users are ready for it if we add it or not.
Here is an example of what is received on server side of the eviction++ in case of https:
```
ACCEPT
-----BEGIN SSL SESSION PARAMETERS-----
MG4CAQECAgMEBAITAQQgwmyx0nutaz5GRezlQlZyP3Ie9MarT2W83bc6yikbiAkE
IN9I+i2ytNY0tRa0CTtpiuMiNUgGQqgw4VAnBujO5Mr5oQYCBGNriRmiBAICHCCk
BgQEAQAAAK4HAgUA+ur2JQ==
-----END SSL SESSION PARAMETERS-----
Shared ciphers:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES …
```

add auth for eviction++

---

Dockerfile

A Trivy scan shows that zlib is vulnerable to a Critical issue CVE-2022-37434, as version 1.2.12-r0 is in the container. By updating Alpine to 3.15.6 we make sure a newer version of zlib is used that is not susceptible to this vulnerability.

Update Alpine Version to Avoid CVE-2022-37434

---

cmd/draino/draino.go
internal/kubernetes/podfilters.go
internal/kubernetes/podfilters_test.go

According to our doc the cordonProtectAnnotation can also be set on the controller of the pod (note that this works only if it is a Statefulset, like for other annotation, limitation that we should fix at some point, not this PR)

cordonProtectAnnotation should also work at controller level

---

internal/kubernetes/drainer.go

When using eviction++ the user should specify the audience if he wants a bearer token to be created. This is done using a query param key=`token-audience`, for example:
```
http://elasticsearch-test-govcloud-1-tools.elasticsearch-test-govcloud-1.local-cluster.local-dc.fabric.dog:8080/api/elasticsearch/evict?token-audience=my-audience
```
For more context about audience:
https://datadoghq.atlassian.net/wiki/spaces/RUNTIME/pages/2649784352/Internal+Service+Authentication#Audience-Configuration
Draino can't decide on the audience. Eviction++ target is defined by the user so we can't know the destination namespace that is behind the URL. This value will be used on the http client side (draino side), and remove from the URL to avoid any side effect on the server parameters validation

token-audience for eviction++

---

internal/groups/index.go
internal/groups/key.go
internal/groups/key_test.go
internal/groups/metrics.go
internal/groups/reconciler.go
internal/groups/reconciler_test.go
internal/groups/runner.go

Building block for scheduling groups:
- indexing: node in a group
- key: interface + key builder based on metadata to have same group than in existing version
- reconciler: ensure that a run is launched for every known node
- groupRunner: run a dedicated go routine (Runner interface) for each group

David.benque/scheduling group runner

---

cmd/draino/draino.go
go.mod
go.sum
internal/kubernetes/analyser/drain_buffer.go
internal/kubernetes/analyser/drain_buffer_test.go
internal/kubernetes/analyser/pdb_analyser_test.go
internal/kubernetes/index/fake.go
internal/kubernetes/index/informer.go
internal/kubernetes/index/pdb.go
internal/kubernetes/index/pdb_test.go
internal/kubernetes/index/pods_test.go

This PR introduce the drain-buffer checker.
Compare to the legacy implementation where drain-buffer is used from schedule to schedule, this new code allows us to check the stability period of the PDBs associated with the pods on the node.
In other words, the drain-buffer will now allow to define for how long we want the system to be stable before engaging a drain.

add drain-buffer checker

---

internal/kubernetes/drainer.go

During some checkups, I’ve noticed that quite some requests to the logs-indexold-coordinator eviction++ endpoint are timing out. [(Logs)](https://app.datadoghq.com/logs?query=service%3Adraino%20message%3A%22custom%20eviction%20endpoint%20response%20error%22%20&agg_q=&cols=kube_cluster_name%2C%40error.message&index=&messageDisplay=inline&sort_m=&sort_t=&stream_sort=time%2Cdesc&top_n=&top_o=&viz=stream&x_missing=&from_ts=1675767396993&to_ts=1675853796993&live=true)
After some discussion with the event-storage-routing team with the following answers: 
1) They want to get rid of this coordinator
2) They have a static timeout of 15s on their side as well.
As this is the only application which is failing regularly, we've decided to keep the static value and just increase it. This will reduce …

increase eviction++ timeout to 20s

---

internal/drain_runner/runner.go
internal/kubernetes/drainer.go

The goal is to add more information, so that we can extend this dashboard:
https://ddstaging.datadoghq.com/dashboard/tz4-8hn-gsy/nla-daniel-test?page=0&tpl_var_Node%5B0%5D=ip-10-128-75-167.ec2.internal&from_ts=1677210540000&to_ts=1677213900000&live=false

add failure reason to failed to drain node log

---

internal/kubernetes/drain/simulator.go
internal/kubernetes/drain/simulator_test.go

This improves identification of pod and PDB names in `draino node diagnostics` output

Include pod namespaces eviction failure messages

---

cmd/draino/draino.go
internal/metrics/constants.go
internal/observability/metrics.go
internal/observability/observability.go

Metrics aggregation per Group NG NGNamespace and filter.
Just like for `conditions` is a node is filtered by N filters, it is counted N times. That allow us to do some investigation per filter type.
Not reporting per node to avoid explosion of cardinality.

adding metrics for filters

---

cmd/draino/draino.go
internal/candidate_runner/sorters/node_annotations.go
internal/drain_buffer/drain_buffer.go
internal/drain_runner/metrics.go
internal/drain_runner/pre_processor/pre_activities.go
internal/drain_runner/pre_processor/pre_activities_test.go
internal/kubernetes/config.go
internal/kubernetes/metadata_search.go
internal/kubernetes/metadata_search_test.go
internal/kubernetes/metrics.go
internal/kubernetes/util.go
internal/metrics/constants.go
internal/observability/observability.go
internal/observability/observability_test.go

Add tag `service` to some of the metrics.
The tag `service` will allow us to connect to service catalog for some analysis (who is associated with the service) but also will ease future integration with SDP (push some NLA relevant information to SDP).

add tag service on some metrics

---

cmd/draino/draino.go
internal/kubernetes/drain/simulator.go
internal/kubernetes/drain/simulator_test.go
internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go
internal/kubernetes/util.go
internal/observability/observability.go

This adds support for dry-run eviction requests to custom eviction urls. Previously we would assume they pass simulation and return early. Now if a pod or its controller has the annotation `draino/eviction-api-dry-run-supported`, it will send a request to the same custom eviction url but with an extra parameter in the json payload like how we do it for kubernetes evictions https://github.com/DataDog/draino/blob/133685a72502fd717b6de1d7c1ac7ca814b78755/internal/kubernetes/drain/simulator.go#L221-L229. If the pod is not opted in, then we will continue to pass simulation early.
If the pod is opted-in, it will not perform pdb checks, this is because the eviction api url should be doing all necessary checks, and might not care about pdbs. However, we will check the rate limiter.
I tested this …

Eviction++ dry-run

---

cmd/draino/draino.go
internal/drain_runner/pre_processor/pre_activities.go
internal/drain_runner/pre_processor/pre_activities_test.go
internal/kubernetes/drainer.go
internal/kubernetes/k8sclient/pod_conditions.go
internal/kubernetes/k8sclient/pod_conditions_test.go
internal/kubernetes/util.go
internal/sync/nla_taint_sync.go
internal/sync/nla_taint_sync_test.go
internal/sync/reconciler.go

For pre-activities, our users might only care about specific pod annotations. In our current setup, they would have to watch for node updates, check if the taint was added, then figure out if the node is hosting a pod they care about, and finally trigger the update mechanism. This makes the whole process much more complex than expected.
Therefore, we've decided to create a new condition on all pods that have pre-activities assigned. This condition should always be in sync with the NLA node taint, so that the operators can react properly.

feature: sync node taint to pod condition

---

internal/kubernetes/drain/simulator.go

This will make sure that we never print empty event messages, like:
```
Drain simulation failed: Cannot drain pod 'minsize-nodeholder/fei-redis-cluster-fei-all-blue-us-east-1c-55cd77fb5b-ptr55', because:
```

fix: add more simulation reasons, to prevent empty events
