DataDog/draino

internal/kubernetes/drainSchedule.go
internal/kubernetes/eventhandler.go

Fixing upstream issue # 103 
Bad error message when trying to erase a schedule that do not exist.

David.benque/issue 103

---

cmd/draino/draino.go
internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go
internal/kubernetes/eventhandler.go
internal/kubernetes/eventhandler_test.go
internal/kubernetes/limiter.go
internal/kubernetes/limiter_test.go
internal/kubernetes/podfilters.go
internal/kubernetes/podfilters_test.go
internal/kubernetes/util.go
internal/kubernetes/watch.go

Removed a call to apiserver that was not cached and that brings no value.
Improved observability by adding new metrics and tags.
Enhance logic in `HandleNode` to avoid going through drain schedule again if we already have a failed or completed drain marked for the node.

Fix memory problem + improve observability

---

cmd/draino/draino.go
internal/kubernetes/drainer.go
internal/kubernetes/limiter.go

When there are too much nodes on a cluster that are cordon and drain but blocked (minSize>0 in NG), draino may ask for too many node replacement at once. This lead to many pending pods and the CA scales up slowly because most of the time each node is for a different NG... In the end the scale up capability of the CA is degraded for application: CA can do one NG at a time (one NG per main loop).
To leave scale up slots to application we are going to limit draino node replacement requests. By default it is set to 2 nodes per hours.

add node replacement limiter

---

cmd/draino/draino.go
internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go

see details in multi-line commit message

fix TestDrain/PodEvictionNotAllowed

---

internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go

do not evict terminating pods

---

cmd/draino/draino.go
internal/kubernetes/drainer.go
internal/kubernetes/eventhandler.go
internal/kubernetes/observability.go

https://datadoghq.atlassian.net/browse/COMPUTE-1113
Adding some indicator in observability for:
- opt-in feature
- drain status

add drainStatus observability

---

cmd/draino/draino.go
internal/kubernetes/podfilters.go
internal/kubernetes/podfilters_test.go

There is not reason for blocking cordon or drain because of a pod that is already completed.

do not attempt to filter pods that are Succeeded/Failed

---

internal/kubernetes/drainer.go
internal/kubernetes/drainer_test.go

The goal of the PR is to use a custom API endpoint.
The first test are done with ElasticSearch and the indexingCoordinator toolbax that act as an operator for the ES cluster.
More details about the test:
https://datadoghq.atlassian.net/wiki/spaces/~960205474/pages/1014531278/Indexing+eviction+API+-+David+-+Corentin
Reference:
https://datadoghq.atlassian.net/browse/COMPUTE-959

custom eviction endpoint

---

internal/kubernetes/observability.go

Fixing timeout value and adding some logs.

fix timeout value (missing unit)

---

Makefile
cmd/draino/draino.go
internal/kubernetes/blocker.go
internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/drainer.go
internal/kubernetes/eventhandler.go
internal/kubernetes/limiter.go
internal/kubernetes/limiter_test.go
internal/kubernetes/watch.go

Add a dedicated structure for global blocker.
Add observability on global blocker(s).

Add a dedicated structure for global blockers + observability

---

cmd/draino/draino.go
internal/kubernetes/podfilters.go
internal/kubernetes/podfilters_test.go
internal/kubernetes/util.go
internal/kubernetes/watch.go

Thanks to that PR the annotation can now be placed on the STS instead of each pod for some opt-in features.

opt-in annotation on sts

---

internal/kubernetes/drainSchedule.go
internal/kubernetes/drainSchedule_test.go
internal/kubernetes/limiter_test.go

Array was being made randomly from a map. Stably making the array now.
Also making a completely new copy of the objects each time they're asked
for
Showed that this was failing before: https://gitlab.ddbuild.io/DataDog/draino/-/jobs/95577059
Ran it `100` times and there were `42` failures.
After ran it `100` times and no failures: https://gitlab.ddbuild.io/DataDog/draino/-/jobs/95596061

Fix flaky test

---

internal/kubernetes/drainSchedule.go
internal/kubernetes/drainer.go
internal/kubernetes/eventhandler.go
internal/kubernetes/limiter.go

Added information in some cases, reworded, consistent capitalization,
etc. Done while creating
https://datadoghq.atlassian.net/wiki/spaces/~960205474/pages/2251949026/Draino+and+Node+Problem+Detector+Event+Inventory

Minor improvements to events

---

internal/kubernetes/event_util.go

Fix variadic arg bug with centralized events

---

cmd/draino/draino.go
internal/kubernetes/k8sclient/rate_limit.go

pr #61 introduced an issue where we were throttling on startup due to
the way we use the discovery api to make a request (effectively) per api
group. The throttling happens now because each api group now shares a
rate limiter, whereas before each api group got its own.
pr #62 actually allowed us to see these throttling messages, see
https://github.com/DataDog/draino/pull/62#issuecomment-989138828
Fixing this by setting the burst to something higher. The default of
`10` is lower than we want anyway. This pr sets the burst to `150`

Correctly configure qps and burst

---

internal/kubernetes/observability.go

Counting in-scope resource by allocatable CPU instead of node count.
This should give a better idea of the progress of in-scope in a context where we are binpacking more and more applications

add CPU metrics to count in-scope resources

---

internal/kubernetes/drainer.go

Due to node-pre-provisioning clean-up, we need to handle a new value for the label.
Other option would be to get rid of that value on the NMC side when cleanup is performed. @aneesh1 would that be possible?

take into account the 'cleanup' value for the node replacement

---

internal/kubernetes/eventhandler.go

minor annoyance while on support

Add pod namespace to event message

---

.gitlab-ci.yml

Add cnab apply and diff so we can test out changes easier
Similar pr: https://github.com/DataDog/k8s-nodegroups/pull/496
TODO: test

Add compute delivery scripts

---

cmd/draino/draino.go
internal/candidate_runner/info.go
internal/candidate_runner/runner.go
internal/cli/commands.go
internal/drain_runner/info.go
internal/drain_runner/runner.go
internal/groups/reconciler.go
internal/observability/metrics.go
internal/observability/observability.go

This PR is adding new metrics to monitor drain candidate / drain runner main loops.

add drain candidate runner loop duration to metrics

---

cmd/draino/draino.go
cmd/draino/options.go
internal/kubernetes/analyser/interface.go
internal/kubernetes/analyser/pdb_analyser.go
internal/kubernetes/analyser/pdb_analyser_test.go
internal/kubernetes/analyser/stability_period.go
internal/kubernetes/analyser/stability_period_test.go
internal/kubernetes/drain/simulator.go

Here is a proposition to order nodes to find first the ones that are taking the budget.
Let's remember that the algorithm do not have to be perfect since, later the simulation is done and if it fails we try the next node in the sorted list. In a way it is a best effort to reduce to the need to do simulation.

sorting node to have first node that take the PDB and that are likely to success drain

---

cmd/draino/draino.go
internal/drain_runner/config.go
internal/drain_runner/factory.go
internal/drain_runner/fake.go
internal/drain_runner/pre_processor/node_replacement.go
internal/drain_runner/runner.go

This was [a feature of v1](https://github.com/DataDog/draino/blob/master/internal/kubernetes/eventhandler.go#L409-L424) and we saw the underlaying issue happening on some of our production cluster.

implement ndoe replacer

---

cmd/draino/draino.go
internal/drain_runner/config.go
internal/drain_runner/factory.go
internal/drain_runner/metrics.go
internal/drain_runner/runner.go

If ever we find a node in `drained` or `candidate` with a pod Pending and a PVC attached to the node, then we remove the taint.

add PVC Protector with taint cleaner

---

cmd/draino/draino.go
internal/metrics/constants.go
internal/metrics/metrics.go

metric to help with https://datadoghq.atlassian.net/browse/CMPT-1469

add metrics for draino running and reflecting the mode

---

internal/kubernetes/drain/simulator.go

* fix bug where any error was causing remaining pods to not be simulated
(this was broken only for simulation not cache lookup)
* fix bug where the event on the node was different for the simulation
running and cache lookup case
* stably sort pods to make sure event construction is always the same

Improve node reason produced from cache when simulation fails for pod

---

.gitlab-ci.yml

After https://github.com/DataDog/compute-delivery/pull/119 the vars i removed are no longer needed. I am also adding the update image jobs

Add update image jobs

---

internal/kubernetes/drain/simulator.go
internal/kubernetes/drain/simulator_test.go
internal/kubernetes/drainer.go

through testing found a nil ptr exception, this is when we return nil as resp but an error occurred
This also checks the dry run annotation value, to make sure it is "true"

eviction++ check for dryrun value and nil ptr err bugfix
